In [4]:
import numpy as np 
import pandas as pd
import matplotlib
#%inline matplotlib
a = np.array([100,200,300])
print(type(a))
print(a.shape)
print(a[0], a[2])
a[0]=958
print(a)

<class 'numpy.ndarray'>
(3,)
100 300
[958 200 300]


In [9]:
#create rank 2 array and print the there value and shape 




b = np.array([[4,5,6],[9,7,6]])
print(b)
print(b.shape)
print(type(b))

[[4 5 6]
 [9 7 6]]
(2, 3)
<class 'numpy.ndarray'>


In [10]:
x= np.array([[1,2],[3,4]], dtype=np.float64)
y= np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [20]:
print(x-y)
print(np.subtract(x,y))
print(np.multiply(x,y))
print(x*y)
print(np.divide(x,y))
print(x/y)
print(np.sqrt(x))
print(x.dot(y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19. 22.]
 [43. 50.]]


In [ ]:
x= np.array([[4,7],[5,9]], dtype=np.float64)
x= np.array([[6,73],[2,5]], dtype=np.float64)


In [24]:
#slicing 
#[9,8,7,6]
#[5,3,2,6]
#[10,8,9,6]

a = np.array ( [[9,8,7,6], [5,3,2,6], [10,8,9,6]])
print(a[0:2,1:3])

[[8 7]
 [3 2]]


In [33]:
rank2=np.array([[3,9,8,7,6],[2,5,4,3,2],[9,10,8,6,4]])
print(rank2)
print('a',rank2[0:4])
print('b',rank2[:,3:5])
print('c', rank2[0:2, 2:4])
print('d', rank2[0,:])

[[ 3  9  8  7  6]
 [ 2  5  4  3  2]
 [ 9 10  8  6  4]]
a [[ 3  9  8  7  6]
 [ 2  5  4  3  2]
 [ 9 10  8  6  4]]
b [[7 6]
 [3 2]
 [6 4]]
c [[8 7]
 [4 3]]
d [3 9 8 7 6]


In [38]:
a=np.array([[20,19,18],[17,16,15],[14,13,12],[11,10,9]])
print(a,a.shape)
b= np.array([0,2,1,0])
print(b)
#select one element from each row of a using the incidence in b 
print(a[np.arange(4),b])

[[20 19 18]
 [17 16 15]
 [14 13 12]
 [11 10  9]] (4, 3)
[0 2 1 0]
[20 15 13 11]


In [42]:
#select one element from each row of using the indices in t 
t = np.array([1,2,0,1])
print(a[np.arange(4),t])

[19 15 14 10]


In [46]:
#indices 
u = np.array([0,1,1,2])
print(a[np.arange(4),u])

#mutation
a[np.arange(4),u]+=5
print(a)

[20 16 13  9]
[[25 19 18]
 [17 21 15]
 [14 18 12]
 [11 10 14]]


In [48]:
t = np.array([1,2,0,1])
a[np.arange(4),t]*=2
print (a)

[[25 76 18]
 [17 21 60]
 [56 18 12]
 [11 40 14]]


In [50]:
#boolean
a= np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)
print(a[bool_idx])


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [53]:
print(np.sum(a))
print(np.sum(a,axis=0)) #adds only first row

21
[ 9 12]


In [61]:
arr=np.arange(87,156)
print(arr)
arr1=np.arange(156).reshape((2,2)
print(arr1)

SyntaxError: invalid syntax (<ipython-input-61-796c0c500db3>, line 4)

In [ ]:
import pandas as pd
a = np.array([1,2,3,4])
series=pd.Series([1,2,3,4])
print(series.)